apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: uiuq/diario-online-backend:4
        ports:
          - containerPort: 8080
